baseURL = 'https://svensvx.github.io/interestingreads/'
languageCode = 'en-us'
title = 'Interesting Reads'
minify = true
disableHugoGeneratorInject = true

[pagination]
  pagerSize = 999

[taxonomies]
  tag = "tags"
  category = "categories"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[params]
  description = "A curated collection of articles from around the web."
  author = "Sven"
  copyright = ""
  logo = "books.png"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20
